name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Setting an environment variable with the value of a configuration variable
  SERVER_ADDRESS: ${{ vars.SERVER_ADDRESS }}
  TOKEN: ${{ vars.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore 
    - name: Test
      run: dotnet test --verbosity detailed
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: SpiceDb/SpiceDb.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}  